import { supabase } from '../utils/supabase';
import { GoogleGenAI } from '@google/genai';

// Initialize the API (relies on process.env.GEMINI_API_KEY)
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

export async function generateOptimizationRecommendations(orgId: string) {
    try {
        // 1. Fetch all active licenses and assignments for the org
        const { data: licenses, error: licError } = await supabase
            .from('licenses')
            .select('id, platform, plan_name, cost_per_seat, seats_purchased, seats_used, renewal_date')
            .eq('org_id', orgId);

        if (licError || !licenses) throw licError || new Error('Failed to fetch licenses');

        if (licenses.length === 0) {
            return { message: "No licenses found to optimize.", data: [] };
        }

        const { data: assignments, error: assignError } = await supabase
            .from('license_assignments')
            .select('license_id, user_email, status, last_active_at, licenses!inner(org_id)')
            .eq('licenses.org_id', orgId);

        if (assignError) throw assignError;

        // 2. Prepare context for the LLM
        const licenseSummary = licenses.map(l => ({
            id: l.id,
            platform: l.platform,
            plan: l.plan_name,
            cost: l.cost_per_seat,
            purchased: l.seats_purchased,
            used: l.seats_used,
            renewal_date: l.renewal_date,
            users: assignments
                ?.filter(a => a.license_id === l.id)
                .map(a => ({ email: a.user_email, status: a.status, last_active: a.last_active_at })) || []
        }));

        const prompt = `
You are an expert SaaS cost optimization AI.
Analyze the following license data for a company and generate targeted cost-saving recommendations.
Look for:
- Idle or unused seats where 'purchased' > 'used'. (Type: "remove")
- Users with 'status' = 'idle' or completely inactive for a long time. (Type: "remove")
- Expensive plans where multiple users could be consolidated or downgraded. (Type: "downgrade" or "consolidate")

Return your analysis as a strict JSON array of objects. Do not wrap it in markdown block quotes. Just the raw JSON array.
Each object must have the exact following structure:
{
  "license_id": "the uuid of the license, or null if it's a general consolidation spanning multiple",
  "type": "downgrade" OR "remove" OR "consolidate",
  "title": "A short, actionable title e.g. 'Remove 5 Unused Slack Seats'",
  "description": "A clear 1-2 sentence explanation of why this action is recommended.",
  "platform": "The name of the platform e.g. Slack",
  "estimated_savings": a generic numerical float value representing monthly savings (e.g. 150.00)
}

Data to analyze:
${JSON.stringify(licenseSummary, null, 2)}
`;

        // 3. Call Gemini
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                temperature: 0.1, // Keep it factual and deterministic
                responseMimeType: "application/json",
            }
        });

        const rawText = response.text || "[]";
        let recommendations = [];
        try {
            // Parse JSON response
            recommendations = JSON.parse(rawText);
        } catch (e) {
            console.error("Failed to parse Gemini response as JSON:", rawText);
            throw new Error('AI returned malformed JSON');
        }

        if (!Array.isArray(recommendations)) {
            recommendations = [];
        }

        // 4. Save to Database
        const dbInserts = recommendations.map((rec: any) => ({
            org_id: orgId,
            license_id: rec.license_id || null,
            type: rec.type,
            title: rec.title,
            description: rec.description,
            platform: rec.platform,
            estimated_savings: rec.estimated_savings || 0,
            status: 'pending'
        }));

        if (dbInserts.length > 0) {
            const { error: upsertError } = await supabase
                .from('optimization_recommendations')
                .insert(dbInserts); // Using insert here because ID is generated by DB

            if (upsertError) {
                console.error("Failed to save recommendations to DB:", upsertError);
            }
        }

        return {
            status: "success",
            message: `Generated ${recommendations.length} recommendations.`,
            total_savings: dbInserts.reduce((sum, r) => sum + r.estimated_savings, 0),
            data: recommendations
        };

    } catch (error: any) {
        console.error('Optimization Engine Error:', error);
        throw error;
    }
}
