[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["rm -rf dist", "npx tsc --project tsconfig.json"]

[start]
cmd = "node dist/index.js"